SELECT
/* MODIFY THE FOLLOWING LINES TO CHOOSE THE PERIODS FOR THIS REPORT */
    CONCAT(
        YEAR(FROM_UNIXTIME(timecreated)),
        '-',
        LPAD(WEEK(FROM_UNIXTIME(timecreated)), 2, '0')
    ) AS periodid,
/* MODIFY THE FOLLOWING LINES TO CHOOSE THE SUBIDS AND VALUES FOR THIS REPORT OR PROVIDE `'' AS subid` */
    '' AS subid,
    COUNT(id) AS periodvalue,
/* DO NOT CHANGE THE FOLLOWING LINES */
    MAX(timecreated) AS lasttimecreated
FROM {local_stats}
WHERE
    timecreated > ?
/* MODIFY THE FOLLOWING LINE TO MATCH YOUR PERIOD DURATION */
    AND timecreated < UNIX_TIMESTAMP(CURDATE() - INTERVAL WEEKDAY(CURDATE()) DAY)
/* MODIFY THE FOLLOWING LINE TO SELECT THE LOG ITEMS RELEVANT TO YOUR REPORT */
    AND path LIKE '/admin/settings.php'
/* DO NOT CHANGE THE FOLLOWING LINES */
GROUP by periodid,subid
ORDER by periodid